### ISSUE TITLE
Guys, who checked, does it work normally?

### ISSUE THREAD

**Issue by Theslandybrain** [YarmolenkoD/moonbix#1]
Guys, who checked, does it work normally?

**Comment by Inquisitor007** [comment]
Error occurred during getting user info: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.binance.com/bapi/growth/v1/friendly/growth-paas/mini-app-activity/third-party/user/user-info')

**Comment by YarmolenkoD** [comment]
@Inquisitor007 @Theslandybrain 

Hey, the bot still in development :) 

But for now you can try my bot for [Boinkers](https://t.me/boinker_bot/boinkapp?startapp=boink355876562) game - [github](https://github.com/YarmolenkoD/boinkers)
