### ISSUE TITLE
Игры не играет?

### ISSUE THREAD

**Issue by Inquisitor007** [YarmolenkoD/moonbix#11]
Выпилили игры?

**Comment by YarmolenkoD** [comment]
@Inquisitor007 пока что нет, в процессе.

**Comment by Inquisitor007** [comment]
Добавили игры? Спасибо
Но почему так мало поинтов за игру засчитывает?
У меня выходит 85-130, но руками выходит зарабатывать больше. По 200-300.

**Comment by YarmolenkoD** [comment]
@Inquisitor007 Сейчас должно больше поинтов получать. Залил апдейт. Попробуй стянуть последние изменения и перезапустить.

**Comment by Inquisitor007** [comment]
> @Inquisitor007 Сейчас должно больше поинтов получать. Залил апдейт. Попробуй стянуть последние изменения и перезапустить.

Да, побольше стало. Теперь около 130-200.
Спасибо за труды 👍
