### ISSUE TITLE
i got new error here, Task-38

### ISSUE THREAD

**Issue by 0xTaaa** [YarmolenkoD/moonbix#12]
Task exception was never retrieved future: <Task finished name='Task-38' coro=<Client. handle_up dates) done, defined at / root/moonbix-p/moon/lib/python3.10 /site-packages/pyrogram/client.py:535> exception=ValueError(
'Peer id invalid: -1002155049133')>

**Comment by YarmolenkoD** [comment]
@0xTaaa Could you provide more info about it and make some screenshot of terminal logs please? Also try to install latest updates from github and rerun it again.

**Comment by 0xTaaa** [comment]
> @0xTaaa Could you provide more info about it and make some screenshot of terminal logs please? Also try to install latest updates from github and rerun it again.

check this screenshot, ive use latest commit
![IMG_4987](https://github.com/user-attachments/assets/c637f61e-ba7c-43d7-937e-80557497b079)

**Comment by 0xTaaa** [comment]
sorry, its done
![IMG_5011](https://github.com/user-attachments/assets/725aa8c1-0e8e-40c5-b5aa-2be2c6ae3935)
