### ISSUE TITLE
Problem opening the database file

### ISSUE THREAD

**Issue by azizbek-777** [YarmolenkoD/moonbix#15]
![photo_2024-09-24_10-01-00](https://github.com/user-attachments/assets/6ae643af-b9b1-4af3-8e8a-493f50b5be84)

**Comment by YarmolenkoD** [comment]
@azizbek-777 You need to update your .env file.

Example:

API_ID=27******
API_HASH=220***52133b******e68df92f***

USE_REF=True
REF_ID=ref_111111111

ENABLE_AUTO_TASKS=True
ENABLE_AUTO_PLAY_GAMES=True

USE_RANDOM_DELAY_IN_RUN=True
RANDOM_DELAY_IN_RUN=[5, 40]

USE_PROXY_FROM_FILE=True
