### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by dimscm** [YarmolenkoD/moonbix#17]
![Screenshot 2024-09-24 203305](https://github.com/user-attachments/assets/2bbf7e3d-04e5-41c7-80ad-ec0c3b317c12)
How what's wrong with this?

**Comment by camillo1991** [comment]
I solve it, y need to change ref id, to set account ChatID

**Comment by dimscm** [comment]
account ChatID? where to get this?

**Comment by YarmolenkoD** [comment]
@dimscm Please provide your .env file. 
@camillo1991 And you please.

**Comment by YarmolenkoD** [comment]
It should looks like this:

API_ID=271222222
API_HASH=1111111813c6b17e61111111

USE_REF=True
REF_ID=ref_355876562

ENABLE_AUTO_TASKS=True
ENABLE_AUTO_PLAY_GAMES=True

USE_RANDOM_DELAY_IN_RUN=True
RANDOM_DELAY_IN_RUN=[5, 40]

USE_PROXY_FROM_FILE=True

**Comment by YarmolenkoD** [comment]
@dimscm @camillo1991 And also try install latest changes and rerun it please.

**Comment by camillo1991** [comment]
REF_ID=355876562 (your main account chat id, from bot https://t.me/chatIDrobot)
