### ISSUE TITLE
Question url

### ISSUE THREAD

**Issue by BrandonWhitee** [YarmolenkoD/moonbix#18]
Hello, sorry for my question. I don't understand how you got GET request for this url "https://moonbix-server-9r08ifrt4-scriptvips-projects.vercel.app/moonbix/api/v1/play". The network in chrome don't have this url.

**Comment by YarmolenkoD** [comment]
@BrandonWhitee Already fixed it. Please install latest changes and rerun please.

**Comment by BrandonWhitee** [comment]
> @BrandonWhitee Already fixed it. Please install latest changes and rerun please.

Thanks a lot
