### ISSUE TITLE
Played the game, but didn’t get the reward

### ISSUE THREAD

**Issue by 0xTaaa** [YarmolenkoD/moonbix#21]
check this screenshot, no reward for auto play game

![IMG_5020](https://github.com/user-attachments/assets/028c056e-ce24-4161-9a06-e9a256d120b8)

**Comment by dimscm** [comment]
![image](https://github.com/user-attachments/assets/9bac1cdf-203f-458a-a021-7b938be047ad)
Mee too

**Comment by YarmolenkoD** [comment]
@dimscm  @0xTaaa  
Hey guys! Workig on this. Thanks for feedback!

**Comment by YarmolenkoD** [comment]
@0xTaaa @dimscm Already fixed. Please install latest changes.

**Comment by 0xTaaa** [comment]
> @0xTaaa @dimscm Already fixed. Please install latest changes.

got this after git pull
Traceback (most recent call last):
  File "/root/moonbix-p/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/moonbix-p/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/moonbix-p/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/root/moonbix-p/bot/core/tapper.py", line 40, in <module>
    from bot.utils.generate import generate_game_data
  File "/root/moonbix-p/bot/utils/generate.py", line 4, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by kohutiv** [comment]
> > @0xTaaa @dimscm Already fixed. Please install latest changes.
> 
> got this after git pull Traceback (most recent call last): File "/root/moonbix-p/main.py", line 4, in from bot.utils.launcher import process File "/root/moonbix-p/bot/utils/**init**.py", line 2, in from . import launcher File "/root/moonbix-p/bot/utils/launcher.py", line 12, in from bot.core.tapper import run_tapper File "/root/moonbix-p/bot/core/tapper.py", line 40, in from bot.utils.generate import generate_game_data File "/root/moonbix-p/bot/utils/generate.py", line 4, in from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'

pip3 uninstall crypto 
pip3 install pycryptodome

**Comment by 0xTaaa** [comment]
> > > @0xTaaa @dimscm Already fixed. Please install latest changes.
> > 
> > 
> > got this after git pull Traceback (most recent call last): File "/root/moonbix-p/main.py", line 4, in from bot.utils.launcher import process File "/root/moonbix-p/bot/utils/**init**.py", line 2, in from . import launcher File "/root/moonbix-p/bot/utils/launcher.py", line 12, in from bot.core.tapper import run_tapper File "/root/moonbix-p/bot/core/tapper.py", line 40, in from bot.utils.generate import generate_game_data File "/root/moonbix-p/bot/utils/generate.py", line 4, in from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'
> 
> pip3 uninstall crypto pip3 install pycryptodome

please add it to requirements.txt

**Comment by YarmolenkoD** [comment]
Done

**Comment by 284267** [comment]
I invited user B, who got 2000 points a day, but my account didn't show 10% bonus points. Does this mean that the points for mining in B are nothing! It's just a number. When user B gets points for manual game mining, I can get 10% reward. This is a fatal problem that we need to understand.
