### ISSUE TITLE
Pls give me advice. What kind of problem is this?

### ISSUE THREAD

**Issue by ROmChiikk** [YarmolenkoD/moonbix#23]
![photo_5449582280898109952_y](https://github.com/user-attachments/assets/db5316bd-15d6-4a83-96ff-4fd22f656200)

API ID and HASH I already put to the .env file, but problem is'n disappeared.
It wrote 3 keys error, what the keys is that. What am I doing wrong. Thanks for all in advice

**Comment by YarmolenkoD** [comment]
@ROmChiikk Hey, could you send your ENV file please

**Comment by ROmChiikk** [comment]
API_ID=23527055
API_HASH=ac06899965043dc3655f88beb923920b

ENABLE_AUTO_TASKS=False
ENABLE_AUTO_PLAY_GAMES=True

USE_RANDOM_DELAY_IN_RUN=True
RANDOM_DELAY_IN_RUN=[5, 40]

RANDOM_DELAY_BETWEEN_CYCLES=[20, 40, 60, 80]

USE_REF=
REF_ID=

USE_PROXY_FROM_FILE=True


Sorry, but i can't load directly env file here due to policy of Git. It writes @We don't support that file type.
But there is the code from .env

I'm grateful to you

**Comment by ROmChiikk** [comment]
Don't look at length of ID and HASH, I have right lenght those two numbers in my .env. Just in security reason I deleted last part of this numbers. Just in case. because I completely nothing make sence in this, and don't know what data in important, and what data is unimportant. I hope you understand correctly my anxiety.

**Comment by YarmolenkoD** [comment]
Looks good

**Comment by YarmolenkoD** [comment]
Could you try to re install the project with latest updates and rerun it again please ? If it will not help, I'l try to resolve your issue.

Thanks!

**Comment by YarmolenkoD** [comment]
@ROmChiikk

**Comment by ROmChiikk** [comment]
@YarmolenkoD okey I will try thanks you bro. 
Спасибо тебе большое сейчас попробую переустановить.

**Comment by nevs83** [comment]
> API_ID=235270 API_HASH=ac06899965043dc3655f88beb9239
> 
> ENABLE_AUTO_TASKS=False ENABLE_AUTO_PLAY_GAMES=True
> 
> USE_RANDOM_DELAY_IN_RUN=True RANDOM_DELAY_IN_RUN=[5, 40]
> 
> RANDOM_DELAY_BETWEEN_CYCLES=[20, 40, 60, 80]
> 
> USE_REF= REF_ID=
> 
> USE_PROXY_FROM_FILE=True
> 
> Sorry, but i can't load directly env file here due to policy of Git. It writes @we don't support that file type. But there is the code from .env
> 
> I'm grateful to you

ты для чего свой токен палишь та?

**Comment by ROmChiikk** [comment]
@YarmolenkoD Sorry for interrapting, but problem is still remains.
![image](https://github.com/user-attachments/assets/769db3f7-ba50-4a83-b00e-b70efe2da1e0)

**Comment by ROmChiikk** [comment]
I want to add my responce. I reinstall Python. Early I have a python version 3.12, turn out. Reinstallation to 3.10 version bring me some another problem. Check this out please. What the reason of this exception? Thanks
![image](https://github.com/user-attachments/assets/34cf4306-8f98-4216-973d-fcedc22aeda4)

**Comment by nevs83** [comment]
> I want to add my responce. I reinstall Python. Early I have a python version 3.12, turn out. Reinstallation to 3.10 version bring me some another problem. Check this out please. What the reason of this exception? Thanks ![image](https://private-user-images.githubusercontent.com/109798870/370846192-34cf4306-8f98-4216-973d-fcedc22aeda4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTQxMzcsIm5iZiI6MTcyNzI5MzgzNywicGF0aCI6Ii8xMDk3OTg4NzAvMzcwODQ2MTkyLTM0Y2Y0MzA2LThmOTgtNDIxNi05NzNkLWZjZWRjMjJhZWRhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxOTUwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWFhYzRlZjI5MzExMmIwZDViZGFmZjRmZmY2NGViMDc4ZWE0YTlmOGFlMWJkNzY2OGQ4Y2JhYTdkNjFkYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XYvaAsS5iZ0omU6TdcY9OQmBAEATe6U_1m0Les6xzWg)

в пути кириллица. имя пользователя

**Comment by nevs83** [comment]
git clone https://github.com/YarmolenkoD/moonbix.git
cd moonbix
python -m venv venv
venv\Scripts\activate
pip install -r requirements.txt
copy .env-example .env
# Here you must specify your API_ID and API_HASH, the rest is taken by default
python main.py


выполни и будет счастье

**Comment by YarmolenkoD** [comment]
@nevs83 Спасибо!

@ROmChiikk Попробуй сделать все так как описал он, надеюсь это поможет, если нет, то пиши снова, будем решать ) 

Так же в случае если долго не отвечаю то можешь дублировать свои вопросы в чат Hidden Code

**Comment by ROmChiikk** [comment]
@YarmolenkoD спасибо большое. Я разобрался. В начале питон стоял более новой версии, я переустановил, потом путь к питону был не верный. Ваш скрипт работает безотказно. Проблема была на моей стороне спасибо большое за обратную связь быструю.
