### ISSUE TITLE
Bot not play the game

### ISSUE THREAD

**Issue by dhn123** [YarmolenkoD/moonbix#25]
![IMG_20240925_221602](https://github.com/user-attachments/assets/c7157101-fd73-4968-b394-94aa60e8062c)
Auto play game was enabled but the bot not playing game.

**Comment by nevs83** [comment]
> ![IMG_20240925_221602](https://private-user-images.githubusercontent.com/182245022/370792258-c7157101-fd73-4968-b394-94aa60e8062c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODQwOTksIm5iZiI6MTcyNzI4Mzc5OSwicGF0aCI6Ii8xODIyNDUwMjIvMzcwNzkyMjU4LWM3MTU3MTAxLWZkNzMtNDk2OC1iMzk0LTk0YWE2MGU4MDYyYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNzAzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjA1OWQzNmQwZDcwMDExOWNhZjcyNDgzMDQyMzA2ZGM5NGQ5ZTEwODEzZWM4OTVjNDFhYTM3MmYyMWUzNWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xq_3ynxeSOkX7YDVPmyTVtZDiHgUunc98miVAPVMUWY) Auto play game was enabled but the bot not playing game.

ENABLE_AUTO_PLAY_GAMES=True

**Comment by dhn123** [comment]
> > ![IMG_20240925_221602](https://private-user-images.githubusercontent.com/182245022/370792258-c7157101-fd73-4968-b394-94aa60e8062c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODQwOTksIm5iZiI6MTcyNzI4Mzc5OSwicGF0aCI6Ii8xODIyNDUwMjIvMzcwNzkyMjU4LWM3MTU3MTAxLWZkNzMtNDk2OC1iMzk0LTk0YWE2MGU4MDYyYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNzAzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjA1OWQzNmQwZDcwMDExOWNhZjcyNDgzMDQyMzA2ZGM5NGQ5ZTEwODEzZWM4OTVjNDFhYTM3MmYyMWUzNWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xq_3ynxeSOkX7YDVPmyTVtZDiHgUunc98miVAPVMUWY) Auto play game was enabled but the bot not playing game.
> 
> ENABLE_AUTO_PLAY_GAMES=True

It was enabled but the bot was not play game, it just show my points & my attempts, then sleep.

**Comment by YarmolenkoD** [comment]
@dhn123 Give me your env please, but without private keys like API_HASH and API_ID. Also did you update script with latest changes ?

**Comment by YarmolenkoD** [comment]
@dhn123 Should be like this:

ENABLE_AUTO_TASKS=True
ENABLE_AUTO_PLAY_GAMES=True

USE_RANDOM_DELAY_IN_RUN=True
RANDOM_DELAY_IN_RUN=[5, 40]

USE_PROXY_FROM_FILE=True

**Comment by nevs83** [comment]
> @dhn123 Should be like this:
> 
> ENABLE_AUTO_TASKS=True ENABLE_AUTO_PLAY_GAMES=True
> 
> USE_RANDOM_DELAY_IN_RUN=True RANDOM_DELAY_IN_RUN=[5, 40]
> 
> USE_PROXY_FROM_FILE=True

Возможно у него старая версия бота

**Comment by dhn123** [comment]
> @dhn123 Give me your env please, but without private keys like API_HASH and API_ID. Also did you update script with latest changes ?

i've re-download the bot & it's working fine now. Thank you!!!
