### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by ilkercitikbel** [YarmolenkoD/moonbix#26]
What mistake did I make here? Some py files?
<img width="1051" alt="Ekran Resmi 2024-09-26 10 28 03" src="https://github.com/user-attachments/assets/29077950-d9d3-4d46-b60b-472f7885c2c8">

**Comment by YarmolenkoD** [comment]
@ilkercitikbel This may be related to the version of python. It should be 3.10. If it doesn't work, let me know.

**Comment by YarmolenkoD** [comment]
@ilkercitikbel try this commands too:

git clone https://github.com/YarmolenkoD/moonbix.git
cd moonbix
python -m venv venv
venv\Scripts\activate
pip install -r requirements.txt
copy .env-example .env

**Comment by ilkercitikbel** [comment]
<img width="730" alt="Ekran Resmi 2024-09-26 10 50 21" src="https://github.com/user-attachments/assets/27ff786d-8cdd-4e7e-b8a6-9afc8d904508">
<img width="620" alt="Ekran Resmi 2024-09-26 10 49 28" src="https://github.com/user-attachments/assets/0a5794aa-2a92-4abd-9fc2-8e5dd2461625">
Dear friend. I installed 3.10 and uninstalled 3.12. I couldn't even install the initial files. It should proceed with python3 and pip3 commands. However, I progressed to the end in 3.12, but I could not make such good progress in 3.10.

**Comment by ilkercitikbel** [comment]
<img width="1271" alt="Ekran Resmi 2024-09-26 11 18 42" src="https://github.com/user-attachments/assets/5454da6d-e434-4ab3-886c-81754f1d2c12">
<img width="1271" alt="Ekran Resmi 2024-09-26 11 19 32" src="https://github.com/user-attachments/assets/b4eb4f2b-a87c-4ecb-8a4f-76663555d334">

**Comment by nevs83** [comment]
> <img alt="Ekran Resmi 2024-09-26 11 18 42" width="1271" src="https://private-user-images.githubusercontent.com/39164282/371048300-5454da6d-e434-4ab3-886c-81754f1d2c12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTgxODIsIm5iZiI6MTcyNzM1Nzg4MiwicGF0aCI6Ii8zOTE2NDI4Mi8zNzEwNDgzMDAtNTQ1NGRhNmQtZTQzNC00YWIzLTg4NmMtODE3NTRmMWQyYzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEzMzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNmZkYmJlZWNmODUzNTA0MmZlNjc5OTY1MjJhOTZhNGUxY2E0M2QwYzU5NDMxNDA2ZjNkYmU4NDc1ZjY5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9NDqkMoJE1dFV8FgpW2eLlQktdzlN4axHkehznbtilM"> <img alt="Ekran Resmi 2024-09-26 11 19 32" width="1271" src="https://private-user-images.githubusercontent.com/39164282/371048333-b4eb4f2b-a87c-4ecb-8a4f-76663555d334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTgxODIsIm5iZiI6MTcyNzM1Nzg4MiwicGF0aCI6Ii8zOTE2NDI4Mi8zNzEwNDgzMzMtYjRlYjRmMmItYTg3Yy00ZWNiLThhNGYtNzY2NjM1NTVkMzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEzMzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDIyYjBjYjQzMDBkM2U5ZDViZWRkZDYwODllYzkwMTE2OTAyMmM1OTBlYWExYjIxYjkzNWM1YjZjNmJiMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G4QsQDWdidaNQ5IuAMzOw6V5CFEtGzyTHOJud1vMMk8">

on the mac, creating a venv 
source venv/bin/activate

**Comment by nevs83** [comment]
> Another connect problem :( <img alt="Ekran Resmi 2024-09-26 16 50 26" width="1409" src="https://private-user-images.githubusercontent.com/39164282/371172740-9e75474a-95a6-4d0c-964d-06428d187cd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjIyMTMsIm5iZiI6MTcyNzM2MTkxMywicGF0aCI6Ii8zOTE2NDI4Mi8zNzExNzI3NDAtOWU3NTQ3NGEtOTVhNi00ZDBjLTk2NGQtMDY0MjhkMTg3Y2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0NDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMjE2NTRmZjZkYWJlMjRkYzVkZjE5NGVlOGNkMzcwYTUyZTYxMTljZTlmZmY0NDU5YTljNmY1N2U1NGIwNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.66hdWPth_-SG3qgtYvuW_McpIztzHg0628kInccEBhI">

have you tried without a proxy?

**Comment by YarmolenkoD** [comment]
@ilkercitikbel going to check and fix it. Thanks for feedback.

Also try run project without proxy or change proxy. Because Moonbix blocked some country.
