### ISSUE TITLE
Session creation failed

### ISSUE THREAD

**Issue by eltary** [YarmolenkoD/moonbix#28]
![image](https://github.com/user-attachments/assets/2c779ab0-bae0-46d7-bf84-9b732e838c0f)
When I enter a phone number, this error occurs

**Comment by nevs83** [comment]
> ![image](https://private-user-images.githubusercontent.com/22243156/371176844-2c779ab0-bae0-46d7-bf84-9b732e838c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjMwNDIsIm5iZiI6MTcyNzM2Mjc0MiwicGF0aCI6Ii8yMjI0MzE1Ni8zNzExNzY4NDQtMmM3NzlhYjAtYmFlMC00NmQ3LWJmODQtOWI3MzJlODM4YzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZGJhYjc3MDJmN2Q5NTg2YjVlMDU5NzAxN2Y3M2M5Y2Q0M2MwODFjMjUyNjk5ZjZjOWE0NzdlMGU2M2JlYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OSlqDM7CQtmKMjVAqro5JQ_Unb9iAdgc9hF-7NpHcNg) When I enter a phone number, this error occurs



Have you tried to follow these steps?

git clone https://github.com/YarmolenkoD/moonbix.git
cd moonbix
python -m venv venv
venv\Scripts\activate
pip install -r requirements.txt
copy .env-example .env Here you must specify your API_ID and API_HASH, the rest is taken by default
python main.py

**Comment by eltary** [comment]
I figured out what the problem was, my computer time was out of sync
**BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.**
