### ISSUE TITLE
ERROR ERROR ERROR 

### ISSUE THREAD

**Issue by Gason15** [YarmolenkoD/moonbix#30]
![image](https://github.com/user-attachments/assets/8666e810-2eb9-4382-b5ed-e7970b885dbb)

**Comment by YarmolenkoD** [comment]
@Gason15 Please install latest changes from the repo https://github.com/YarmolenkoD/moonbix and rerun project from scratch. I think you have old version.

**Comment by Gason15** [comment]
> @Gason15 Please install latest changes from the repo https://github.com/YarmolenkoD/moonbix and rerun project from scratch. I think you have old version.


Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

**Comment by YarmolenkoD** [comment]
@Gason15 Issue related to your proxy provider. I can only assume you're using webshare. in which case you need to look at their instructions on how to use their proxies. On their service you need to specify your current IP address in the authorization settings so that the proxies would work.

**Comment by Gason15** [comment]
> @Gason15 Issue related to your proxy provider. I can only assume you're using webshare. in which case you need to look at their instructions on how to use their proxies. On their service you need to specify your current IP address in the authorization settings so that the proxies would work. 

How about Fomat proxy, please.???
