### ISSUE TITLE
can we change the eraninf values?

### ISSUE THREAD

**Issue by danazor** [YarmolenkoD/moonbix#33]
the highest earning in games is 200. every hour at least 2 games get 200 points. is there a way to increase or decrease this limit?

**Comment by nevs83** [comment]
> the highest earning in games is 200. every hour at least 2 games get 200 points. is there a way to increase or decrease this limit?

![image](https://github.com/user-attachments/assets/f29d4577-679f-4ffa-a165-31654a21a42d)

**Comment by YarmolenkoD** [comment]
@nevs83 @danazor I'll add it in next updates. 200 is the most stable value for successfull games, but I can add ENV variable and you can play with values :)

**Comment by YarmolenkoD** [comment]
@nevs83 @danazor Pushed updates with new env variable MAX_GAME_POINTS=200. Recommended is 200, but you can try bigger numbers.

**Comment by YarmolenkoD** [comment]
Done

**Comment by danazor** [comment]
> @nevs83 @danazor Pushed updates with new env variable MAX_GAME_POINTS=200. Recommended is 200, but you can try bigger numbers.

thanks for your update. Just an idea,

can you make points like 
RANDOM_DELAY_BETWEEN_CYCLES Random minutes delay between cycles (default is [20, 40, 60, 80])

i mean more RANDOM_GAME_POINTS [225,220,,215,210,200,...170] ? or is there no need for such a thing?
