### ISSUE TITLE
six module error

### ISSUE THREAD

**Issue by 1flipstar1** [YarmolenkoD/moonbix#35]
![Снимок экрана 2024-09-27 204916](https://github.com/user-attachments/assets/720bc0f6-1114-454c-aa8d-2c363b814f72)
The program does not see module six, although I installed it and even updated it to the latest version

**Comment by YarmolenkoD** [comment]
@1flipstar1 Hey, how you start the script ? run.bat or from terminal ?

**Comment by YarmolenkoD** [comment]
@1flipstar1 
I think it should help you

1) remove venv folder if it exist 

2) USE THE COMMANDS IN TERMINAL:

python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
python3 main.py

**Comment by nevs83** [comment]
> @1flipstar1 I think it should help you
> 
> 1. remove venv folder if it exist
> 2. USE THE COMMANDS IN TERMINAL:
> 
> python3 -m venv venv source venv/bin/activate pip3 install -r requirements.txt python3 main.py

у него винда )

python -m venv venv
venv\Scripts\activate
pip install -r requirements.txt
python main.py

**Comment by nevs83** [comment]
и если будет время позакрывай выполненные проблемы. они сами их не закроют)

**Comment by 1flipstar1** [comment]
@nevs83 @YarmolenkoD уже решил проблему, скрипт работает. А что за проблемы? Я что-то не очень понял. И ещё хотел спросить, а когда скрипт запущен он не открывает окно приложения? Он просто в терминале только отображает результаты?

**Comment by YarmolenkoD** [comment]
@1flipstar1 Да скрипт работает без приложения, работает чисто на запросах на их сервер

**Comment by YarmolenkoD** [comment]
Закрываю как решеное
