### ISSUE TITLE
Too much errors . New installation

### ISSUE THREAD

**Issue by cmeept** [YarmolenkoD/moonbix#37]
Please some help 
![1](https://github.com/user-attachments/assets/e8586c58-90a6-4a9f-8f56-c91f8bf1c7e3)

Please make sure you have the correct access rights
and the repository exists.
No stash entries found.
Starting the bot...
Traceback (most recent call last):
  File "C:\Games\moonbix-master\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\petrk\AppData\Local\Programs\Python\Python311-32\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\petrk\AppData\Local\Programs\Python\Python311-32\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\petrk\AppData\Local\Programs\Python\Python311-32\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Games\moonbix-master\main.py", line 8, in main
    await process()
  File "C:\Games\moonbix-master\bot\utils\launcher.py", line 89, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
                                                                      ^^^^^^^^^^^^^
  File "C:\Games\moonbix-master\bot\utils\launcher.py", line 53, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Games\moonbix-master\bot\utils\launcher.py", line 53, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Games\moonbix-master\venv\Lib\site-packages\better_proxy\proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')
ValueError: Unsupported proxy format: type://user:pass@ip:port
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

**Comment by nevs83** [comment]
> Please some help ![1](https://private-user-images.githubusercontent.com/35558327/371763840-e8586c58-90a6-4a9f-8f56-c91f8bf1c7e3.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NTYyNTcsIm5iZiI6MTcyNzU1NTk1NywicGF0aCI6Ii8zNTU1ODMyNy8zNzE3NjM4NDAtZTg1ODZjNTgtOTBhNi00YTlmLThmNTYtYzkxZjhiZjFjN2UzLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDIwMzkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzIyZmJmMzljMGRjNzA2YjU3MTE1MTQ3M2Y2ZWU0Yzg0NTlkYjU5M2ZkZDI4MzNiMDQxMzkyYTg5NjVkNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zD5KC1o1pulpR-ZKMOYmyZei11CBuJWOP9d1eXbozLM)
> 
> Please make sure you have the correct access rights and the repository exists. No stash entries found. Starting the bot... Traceback (most recent call last): File "C:\Games\moonbix-master\main.py", line 13, in asyncio.run(main()) File "C:\Users\petrk\AppData\Local\Programs\Python\Python311-32\Lib\asyncio\runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\petrk\AppData\Local\Programs\Python\Python311-32\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\petrk\AppData\Local\Programs\Python\Python311-32\Lib\asyncio\base_events.py", line 654, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Games\moonbix-master\main.py", line 8, in main await process() File "C:\Games\moonbix-master\bot\utils\launcher.py", line 89, in process logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies") ^^^^^^^^^^^^^ File "C:\Games\moonbix-master\bot\utils\launcher.py", line 53, in get_proxies proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Games\moonbix-master\bot\utils\launcher.py", line 53, in proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Games\moonbix-master\venv\Lib\site-packages\better_proxy\proxy.py", line 52, in from_str raise ValueError(f'Unsupported proxy format: {proxy}') ValueError: Unsupported proxy format: type://user:pass@ip:port done PLEASE EDIT .ENV FILE Press any key to continue . . .

required python 3.10
