### ISSUE TITLE
webshare

### ISSUE THREAD

**Issue by Pawansingh333** [YarmolenkoD/moonbix#43]
Can someone please explain why, 4-5 days ago, Webshare proxies were working with Pyrogram bots like Memefi, Hamster, Tapswap, etc., but now even fresh Webshare proxies don't work? However, the same proxies work with the bot that runs using query ID. Please let me know why this is happening and how Webshare proxies can work like before. Thanks

**Comment by maxpaynew0w** [comment]
I haven't encountered this issue with Webshare. I have at least five bots configured with the API/hash, and they work perfectly.

**Comment by Pawansingh333** [comment]
Thanks for reply im using your bot and getin this Proxy: socks5://ifjittto:36nxfjwllreo@198.23.239.134:6540 | Error: required argument is not an integer please tell me how to fix

**Comment by maxpaynew0w** [comment]
This is not my bot :) try to use HTTP instead of socks5

**Comment by Pawansingh333** [comment]
thanks for replying but http://38.154.227.167:5868:ifjittto:36nxfjwllreo and get this 


Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Connection failed! Trying again...
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

**Comment by maxpaynew0w** [comment]
Please add your public IP address to the 'IP Authorizations' section under Proxy Settings in Webshare.
