### ISSUE TITLE
Security Verification before games

### ISSUE THREAD

**Issue by danazor** [YarmolenkoD/moonbix#47]
Hey man, script is stopped play auto game right? also binance added security verification puzzle before games.

Can this be prevented with a script?
![11](https://github.com/user-attachments/assets/0dcd7fb0-4d87-41ec-badf-fce6c7924af6)

**Comment by online** [comment]
Please, read this commit → https://github.com/YarmolenkoD/moonbix/commit/277d7c02e88d93e439f98bb5619f748c81311018
