### ISSUE TITLE
error getting user info

### ISSUE THREAD

**Issue by 0xTaaa** [YarmolenkoD/moonbix#6]
when i run i got this error

Error occurred during getting user info: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.binance.com/bapi/growth/v1/friendly/growth-paas/mini-app-activity/third-party/user/user-info')

**Comment by NamasteIndia** [comment]
![image](https://github.com/user-attachments/assets/799d2e66-fd59-4bef-bd96-f34e81e5481a)

**Comment by NamasteIndia** [comment]
> when i run i got this error
> 
> Error occurred during getting user info: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.binance.com/bapi/growth/v1/friendly/growth-paas/mini-app-activity/third-party/user/user-info') ![IMG_4909](https://private-user-images.githubusercontent.com/50816765/369625373-11c84568-7eab-4a75-8799-7d1866cc9bb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5Mjg2OTcsIm5iZiI6MTcyNjkyODM5NywicGF0aCI6Ii81MDgxNjc2NS8zNjk2MjUzNzMtMTFjODQ1NjgtN2VhYi00YTc1LTg3OTktN2QxODY2Y2M5YmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE0MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZWUxYzdhOGEzYzViMTgxNmZjYjYwNTk5NWJlYzY3Zjk0MzY3MWU2ZDAxYzk5NTUwOWZmYzlkMDYyMjZjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4aICLKAAK9u6S40ITyZIrv-J5se8YORwxSiuFQiOzVg)

hide your ip lol

**Comment by 0xTaaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/49607060/369625580-799d2e66-fd59-4bef-bd96-f34e81e5481a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5Mjg4ODAsIm5iZiI6MTcyNjkyODU4MCwicGF0aCI6Ii80OTYwNzA2MC8zNjk2MjU1ODAtNzk5ZDJlNjYtZmQ1OS00YmVmLWJkOTYtZjM0ZTgxZTU0ODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE0MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTcxMTEyYjgxOGM3MjU1OTYzZjQ0M2FkYTc0ZGYzZWE5Njg5ZGM3ZWJlYTIzZjZlNmZiNjYwZjFmZDhjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q8IJPNMoNlh0URLAsZXzRdfpLsXL2i3_LXPXftGRAQI)

its custom proxy sir😅😅

**Comment by xcybermanx** [comment]
same issue : 

2024-09-21 17:42:31 | ERROR | moonbix | Error occurred during getting user info: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.binance.com/bapi/growth/v1/friendly/growth-paas/mini-app-activity/third-party/user/user-info')
2024-09-21 17:42:33 | INFO | moonbix | 💤 sleep 600 seconds 💤

**Comment by YarmolenkoD** [comment]
@xcybermanx  @NamasteIndia  @0xTaaa The bot is already working now

**Comment by NamasteIndia** [comment]
![Screenshot_20240923-182130_Termius](https://github.com/user-attachments/assets/48d44515-1658-438c-bbc0-2462fd330ac3)

Not fixed

**Comment by YarmolenkoD** [comment]
@NamasteIndia Please reinstall project with latest updates and try run it again. I think it should help.

**Comment by 0xTaaa** [comment]
it’s working, please add auto play the game🙏🏻👨‍🌾
