### ISSUE TITLE
The json_data for login is wrong

### ISSUE THREAD

**Issue by tranngocminh230791** [YarmolenkoD/moonbix#8]
bro, please double check on the def login, the json_data (tg_data) you send was wrong
The result for the login is {'code': '000002', 'message': 'illegal parameter', 'messageDetail': None, 'data': None, 'success': False}

**Comment by YarmolenkoD** [comment]
> bro, please double check on the def login, the json_data (tg_data) you send was wrong
> 
> The result for the login is {'code': '000002', 'message': 'illegal parameter', 'messageDetail': None, 'data': None, 'success': False}

Hey, the bot still in development

**Comment by kamkuakuay** [comment]
![image](https://github.com/user-attachments/assets/a216211a-2b09-4534-8d1a-656100f37ca9)

**Comment by YarmolenkoD** [comment]
@kamkuakuay @tranngocminh230791 The bot is already working now

**Comment by slavon141** [comment]
ModuleNotFoundError: No module named 'loguru'
done
PLEASE EDIT .ENV FILE
сам цей файл:
```
API_ID=1941***
API_HASH=45b8e73***5990***6d5***b1a6431f4

ENABLE_AUTO_TASKS=False
ENABLE_AUTO_PLAY_GAMES=True

USE_RANDOM_DELAY_IN_RUN=True
RANDOM_DELAY_IN_RUN=[5, 40]

USE_REF=False
REF_ID=ref_398784545

USE_PROXY_FROM_FILE=False 
```
What's wrong here?

**Comment by fnursandi** [comment]
![image_2024-09-23_203723670](https://github.com/user-attachments/assets/23a3399e-f9e8-4a85-9d58-4173d7029ccb)
Whats wrong bro?

**Comment by YarmolenkoD** [comment]
@slavon141 please reinstall project with latest updates, and it should help

**Comment by YarmolenkoD** [comment]
@fnursandi It looks like you need to add a sessions folder with the sessions files. Did you choose to run the clicker before you created the sessions?

**Comment by fnursandi** [comment]
> It looks like you need to add a sessions folder with the sessions files. Did you choose to run the clicker before you created the sessions?

That's right I run the clicker before creating a session, how do I create a session?

**Comment by YarmolenkoD** [comment]
@fnursandi Just select create session option with number "2" instead "1", and enter your telegram phone number
